### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by XCZchaos** [zhenyuanlu/awesome-pain-intensity-classification-papers#2]
Dear Author:
    Thank you for your sharing. I am a newcomer in the field of pain, and I need to use private pain data for classification recently. Do you know any open source classic machine learning and deep learning pain classification models? Hope to get your reply.

YiBo Xiong,
Best wish!

**Comment by zhenyuanlu** [comment]
Hi Yibo, all the papers listed in this repository propose ML/DL models, hope this would be helpful
